### ISSUE TITLE
How work "eff->target_position"?

### ISSUE THREAD

**Issue by Mikez2015** [TheComet/ik#13]
Please help me, I cannot understand how the effector position works.
For example, if I want to place child3 in world coordinates (30,30,0), what coordinates should I set for the effector?

![ik](https://user-images.githubusercontent.com/10583925/105659664-e06d6500-5efb-11eb-97de-8f82b3404156.jpg)

**Comment by Mikez2015** [comment]
I tried to set 
eff->target_position = ik.vec3.vec3(-100,0,0);
and got such incomprehensible results:
![ik2](https://user-images.githubusercontent.com/10583925/105662808-38f43080-5f03-11eb-8ffb-c4edc7487f8d.jpg)

I expected the whole line to stretch in the negative x-direction, but it didn't.

**Comment by Mikez2015** [comment]
Solved.

**Comment by Jerryzhangzhao** [comment]
> Solved.

Hi, how do you solve that, I met exactly the same problem!
